/**
 * Screenshot export using html2canvas
 * Lazy-loaded to avoid shipping ~200KB to initial bundle
 */

import { APP } from "@/lib/constants";

export interface ScreenshotOptions {
  format: "png" | "jpg";
  quality?: number; // 0-1, only used for jpg
  scale?: number; // pixel density, default 2 for retina
}

export interface ScreenshotResult {
  success: boolean;
  error?: string;
}

/**
 * Take a screenshot of a DOM element and download it.
 */
export async function captureAndDownload(
  element: HTMLElement,
  options: ScreenshotOptions = { format: "png" },
): Promise<ScreenshotResult> {
  try {
    // Dynamically import html2canvas — keeps it out of the initial bundle
    const { default: html2canvas } = await import("html2canvas");

    const canvas = await html2canvas(element, {
      scale: options.scale ?? 2,
      useCORS: true,
      allowTaint: false,
      backgroundColor: "#ffffff",
      logging: false,
    });

    // Add watermark
    const ctx = canvas.getContext("2d");
    if (ctx) {
      addWatermark(ctx, canvas.width);
    }

    const mimeType = options.format === "jpg" ? "image/jpeg" : "image/png";
    const quality =
      options.format === "jpg" ? (options.quality ?? 0.9) : undefined;

    return await new Promise((resolve) => {
      canvas.toBlob(
        (blob) => {
          if (!blob) {
            resolve({ success: false, error: "Failed to generate image blob" });
            return;
          }

          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = `seo-preview-${Date.now()}.${options.format}`;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          URL.revokeObjectURL(url);

          resolve({ success: true });
        },
        mimeType,
        quality,
      );
    });
  } catch (error) {
    return {
      success: false,
      error:
        error instanceof Error
          ? error.message
          : "Screenshot failed. Please try again.",
    };
  }
}

/**
 * Add branding watermark to canvas context
 */
function addWatermark(
  ctx: CanvasRenderingContext2D,
  canvasWidth: number,
): void {
  const watermarkText = `Generated by SEO Meta Preview — ${APP.url}`;
  const fontSize = 12;
  const padding = 8;
  const watermarkHeight = fontSize + padding * 2;

  // Dark semi-transparent background
  ctx.fillStyle = "rgba(0, 0, 0, 0.6)";
  ctx.fillRect(
    0,
    ctx.canvas.height - watermarkHeight,
    canvasWidth,
    watermarkHeight,
  );

  // White text
  ctx.fillStyle = "#ffffff";
  ctx.font = `${fontSize}px Arial, sans-serif`;
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText(
    watermarkText,
    canvasWidth / 2,
    ctx.canvas.height - watermarkHeight / 2,
  );
}
