import { describe, it, expect, vi, beforeEach } from "vitest";
import { captureAndDownload } from "./screenshot";

// ─── Hoisted mock references ──────────────────────────────────────────────────
// vi.hoisted() runs before module mocks so these variables are available
// inside the vi.mock factory below.
const { mockCtx, mockCanvas, resetMocks } = vi.hoisted(() => {
  const mockCtx = {
    canvas: { height: 400, width: 600 },
    fillStyle: "" as string,
    fillRect: vi.fn(),
    fillText: vi.fn(),
    font: "" as string,
    textAlign: "" as string,
    textBaseline: "" as string,
  };

  const mockCanvas = {
    width: 600,
    height: 400,
    getContext: vi.fn().mockReturnValue(mockCtx),
    toBlob: vi.fn().mockImplementation((callback: (blob: Blob | null) => void) => {
      callback(new Blob(["fake-image-data"], { type: "image/png" }));
    }),
  };

  function resetMocks() {
    mockCtx.fillRect.mockClear();
    mockCtx.fillText.mockClear();
    mockCanvas.getContext.mockClear();
    mockCanvas.toBlob.mockClear();
    // Restore toBlob to success default
    mockCanvas.toBlob.mockImplementation(
      (callback: (blob: Blob | null) => void) => {
        callback(new Blob(["fake-image-data"], { type: "image/png" }));
      },
    );
  }

  return { mockCtx, mockCanvas, resetMocks };
});

// ─── html2canvas module mock ──────────────────────────────────────────────────
vi.mock("html2canvas", () => ({
  default: vi.fn().mockResolvedValue(mockCanvas),
}));

// ─── DOM / URL mocks ──────────────────────────────────────────────────────────
const mockCreateObjectURL = vi.fn().mockReturnValue("blob:fake-url");
const mockRevokeObjectURL = vi.fn();
Object.defineProperty(URL, "createObjectURL", {
  value: mockCreateObjectURL,
  writable: true,
});
Object.defineProperty(URL, "revokeObjectURL", {
  value: mockRevokeObjectURL,
  writable: true,
});

const mockClick = vi.fn();
const mockAppendChild = vi.fn();
const mockRemoveChild = vi.fn();
const originalCreateElement = document.createElement.bind(document);

vi.spyOn(document, "createElement").mockImplementation((tag: string) => {
  if (tag === "a") {
    const el = originalCreateElement("a");
    el.click = mockClick;
    return el;
  }
  return originalCreateElement(tag);
});

vi.spyOn(document.body, "appendChild").mockImplementation(
  mockAppendChild as typeof document.body.appendChild,
);
vi.spyOn(document.body, "removeChild").mockImplementation(
  mockRemoveChild as typeof document.body.removeChild,
);

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("screenshot", () => {
  beforeEach(() => {
    resetMocks();
    mockClick.mockClear();
    mockAppendChild.mockClear();
    mockRemoveChild.mockClear();
    mockCreateObjectURL.mockClear();
    mockRevokeObjectURL.mockClear();
  });

  // ── SS-01: Successful capture ─────────────────────────────────────────────

  it("SS-01: returns { success: true } on successful capture", async () => {
    const el = document.createElement("div");
    const result = await captureAndDownload(el, { format: "png" });
    expect(result.success).toBe(true);
    expect(result.error).toBeUndefined();
  });

  // ── SS-02: toBlob returns null ────────────────────────────────────────────

  it("SS-02: returns { success: false } when toBlob yields null", async () => {
    const html2canvasMock = await import("html2canvas");
    vi.mocked(html2canvasMock.default).mockResolvedValueOnce({
      ...mockCanvas,
      getContext: vi.fn().mockReturnValue(null),
      toBlob: vi.fn().mockImplementation((cb: (b: Blob | null) => void) => {
        cb(null);
      }),
    } as unknown as HTMLCanvasElement);

    const el = document.createElement("div");
    const result = await captureAndDownload(el, { format: "png" });
    expect(result.success).toBe(false);
    expect(result.error).toBe("Failed to generate image blob");
  });

  // ── SS-03: html2canvas throws ─────────────────────────────────────────────

  it("SS-03: returns { success: false } when html2canvas throws", async () => {
    const html2canvasMock = await import("html2canvas");
    vi.mocked(html2canvasMock.default).mockRejectedValueOnce(
      new Error("Canvas error"),
    );

    const el = document.createElement("div");
    const result = await captureAndDownload(el, { format: "png" });
    expect(result.success).toBe(false);
    expect(result.error).toBeTruthy();
  });

  // ── SS-04: Watermark text contains "Generated by SEO Meta Preview" ─────────

  it("SS-04: watermark fillText is called with 'Generated by SEO Meta Preview'", async () => {
    const el = document.createElement("div");
    await captureAndDownload(el, { format: "png" });

    expect(mockCtx.fillText).toHaveBeenCalled();
    const [calledText] = mockCtx.fillText.mock.calls[0] as [string, ...unknown[]];
    expect(calledText).toContain("Generated by SEO Meta Preview");
  });

  // ── SS-05: Watermark fillRect positioned at canvas bottom ─────────────────
  // watermarkHeight = 12 (fontSize) + 8*2 (padding) = 28
  // fillRect(0, canvasHeight - 28, canvasWidth, 28) → y = 400 - 28 = 372

  it("SS-05: watermark fillRect y-offset equals canvas.height - watermarkHeight", async () => {
    const el = document.createElement("div");
    await captureAndDownload(el, { format: "png" });

    expect(mockCtx.fillRect).toHaveBeenCalled();
    const fillRectArgs = mockCtx.fillRect.mock.calls[0] as [
      number,
      number,
      number,
      number,
    ];
    const [_x, y] = fillRectArgs;
    // watermarkHeight = fontSize(12) + padding*2(16) = 28
    // y should be canvas.height(400) - watermarkHeight(28) = 372
    const expectedY = mockCtx.canvas.height - 28;
    expect(y).toBe(expectedY);
  });

  // ── SS-06: Default format is PNG ──────────────────────────────────────────

  it("SS-06: uses image/png mime type when format is png", async () => {
    const el = document.createElement("div");
    const result = await captureAndDownload(el, { format: "png" });
    expect(result.success).toBe(true);
    // toBlob is called with "image/png" as mime type
    const [, mimeType] = mockCanvas.toBlob.mock.calls[0] as [
      unknown,
      string,
      unknown,
    ];
    expect(mimeType).toBe("image/png");
  });

  // ── SS-07: JPG format uses image/jpeg ────────────────────────────────────

  it("SS-07: uses image/jpeg mime type when format is jpg", async () => {
    const el = document.createElement("div");
    const result = await captureAndDownload(el, { format: "jpg", quality: 0.9 });
    expect(result.success).toBe(true);
    const [, mimeType] = mockCanvas.toBlob.mock.calls[0] as [
      unknown,
      string,
      unknown,
    ];
    expect(mimeType).toBe("image/jpeg");
  });

  // ── SS-08: scale option passed to html2canvas ─────────────────────────────

  it("SS-08: passes scale: 2 (default) to html2canvas when not specified", async () => {
    const html2canvasMock = await import("html2canvas");
    const el = document.createElement("div");
    await captureAndDownload(el, { format: "png" });

    const [, options] = vi.mocked(html2canvasMock.default).mock.calls[
      vi.mocked(html2canvasMock.default).mock.calls.length - 1
    ] as [HTMLElement, Record<string, unknown>];
    expect(options.scale).toBe(2);
  });

  it("SS-08b: passes custom scale to html2canvas when specified", async () => {
    const html2canvasMock = await import("html2canvas");
    const el = document.createElement("div");
    await captureAndDownload(el, { format: "png", scale: 3 });

    const [, options] = vi.mocked(html2canvasMock.default).mock.calls[
      vi.mocked(html2canvasMock.default).mock.calls.length - 1
    ] as [HTMLElement, Record<string, unknown>];
    expect(options.scale).toBe(3);
  });

  // ── SS-09: Download anchor triggered and removed ──────────────────────────

  it("SS-09: click() is called on the download anchor element", async () => {
    const el = document.createElement("div");
    await captureAndDownload(el, { format: "png" });
    expect(mockClick).toHaveBeenCalled();
  });

  it("SS-09b: document.body.appendChild is called with the anchor", async () => {
    const el = document.createElement("div");
    await captureAndDownload(el, { format: "png" });
    expect(mockAppendChild).toHaveBeenCalled();
  });

  it("SS-09c: document.body.removeChild is called (no memory leak)", async () => {
    const el = document.createElement("div");
    await captureAndDownload(el, { format: "png" });
    expect(mockRemoveChild).toHaveBeenCalled();
  });

  // ── SS-03 (non-Error throw): non-Error throw returns generic message ───────

  it("includes error message from thrown Error object", async () => {
    const html2canvasMock = await import("html2canvas");
    vi.mocked(html2canvasMock.default).mockRejectedValueOnce(
      new Error("Out of memory"),
    );
    const el = document.createElement("div");
    const result = await captureAndDownload(el, { format: "png" });
    expect(result.error).toBe("Out of memory");
  });

  it("returns generic error message for non-Error thrown values", async () => {
    const html2canvasMock = await import("html2canvas");
    vi.mocked(html2canvasMock.default).mockRejectedValueOnce("string-error");
    const el = document.createElement("div");
    const result = await captureAndDownload(el, { format: "png" });
    expect(result.success).toBe(false);
    expect(result.error).toBeTruthy();
  });

  // ── URL lifecycle ─────────────────────────────────────────────────────────

  it("calls URL.createObjectURL with a Blob", async () => {
    const el = document.createElement("div");
    await captureAndDownload(el, { format: "png" });
    expect(mockCreateObjectURL).toHaveBeenCalledWith(expect.any(Blob));
  });

  it("calls URL.revokeObjectURL to avoid memory leaks", async () => {
    const el = document.createElement("div");
    await captureAndDownload(el, { format: "png" });
    expect(mockRevokeObjectURL).toHaveBeenCalledWith("blob:fake-url");
  });

  // ── Default options ───────────────────────────────────────────────────────

  it("succeeds with default options (no explicit options passed)", async () => {
    const el = document.createElement("div");
    const result = await captureAndDownload(el);
    expect(result.success).toBe(true);
  });

  it("succeeds with jpg format", async () => {
    const el = document.createElement("div");
    const result = await captureAndDownload(el, { format: "jpg" });
    expect(result.success).toBe(true);
  });
});
