"use client";

import { APP } from "@/lib/constants";

/**
 * Invisible overlay used to add watermark text to screenshots.
 * This component is rendered inside the preview area but positioned
 * at the bottom — html2canvas captures it as part of the image.
 */
export function ScreenshotWatermark() {
  return (
    <div
      aria-hidden="true"
      className="absolute bottom-0 left-0 right-0 bg-black/60 text-white text-[10px] text-center py-1 px-2 font-mono"
      style={{ pointerEvents: "none" }}
    >
      Generated by SEO Meta Preview — {APP.url}
    </div>
  );
}
